<?php
include('../PHPMailer/src/SMTP.php');
include('../PHPMailer/src/PHPMailer.php');
require('../PHPMailer/src/Exception.php');
include('includes/config.php');



$mail = new PHPMailer\PHPMailer\PHPMailer();
if (isset($_POST['reset'])) {
    
    //prevent posting blank value for email
    if (isset($_POST['email']) && !empty($_POST['email'])) {
      $user_email = mysqli_real_escape_string($conn, trim($_POST['email']));
    } else {
      $error = 1;
      $err = "Enter your E-mail";
    }
  $email = $_POST['email'];
    // check if the user exists
    $query = mysqli_query($conn, "SELECT * from `user` WHERE email='" . $email . "'");
    $num_rows = mysqli_num_rows($query);
  
    if ($num_rows > 0) // check if alredy liked or not condition
    {
      $n = date('y');
      $password = bin2hex(random_bytes($n));
      $new_password=substr($password,0,10);
      //Insert Captured information to a database table
      $query = "UPDATE user SET  password=? WHERE  email =?";
      $stmt = $conn->prepare($query);
      //bind paramaters
      $rc = $stmt->bind_param('ss', $new_password, $email);
      $stmt->execute();

$mail->setFrom('companyemail@gmail.com');
$mail->addAddress($email);
$mail->Subject ='E-house Password Reset confirmation';
$mail->Body = '<h2 style="color:Black;">Here is Password Reset</h2>
<p style="color:Blue;">Here is your new password  '.$new_password.' . After login in your can change it.</p>';

$mail->isHTML(true);
$mail->AltBody = "This message is generated by plain text !";
$mail->IsSMTP();
$mail->SMTPSecure = 'ssl';
$mail->Host = 'ssl://smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Port = 465;
$mail->Username = 'companyemail@gmail.com';
$mail->Password = 'passwod';
if(!$mail->send()) {
  echo 'Email is not sent.';
  echo 'Email error: ' . $mail->ErrorInfo;
} else {
  
  echo"<script>alert('Please check your Reset password in your email');</script>";
  
}
}
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="antony">
    <meta name="keywords" content="E-house rental">

    <!-- Title Page-->
    <title>E-house Rental:Admin</title>

    <!-- Fontfaces CSS-->
    <link href="css/font-face.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/theme.css" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <h1>E-house rental</h1>
                            </a>
                        </div>
                        <div class="login-form">


                            <form action="" method="post">
                            <h7>Admin Reset Password</h7>
                                <div class="form-group">
                                    <label>User Email</label>
                                    <input class="au-input au-input--full" type="email" name="email" placeholder="Email">
                                </div>
                                
                                
                                <div class="login-checkbox">
                                    
                                    
                                </div>
                                <input class="au-btn au-btn--block au-btn--green m-b-20"name="reset" value="Reset" type="submit">
                                
                            </form>
                    
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="vendor/slick/slick.min.js">
    </script>
    <script src="vendor/wow/wow.min.js"></script>
    <script src="vendor/animsition/animsition.min.js"></script>
    <script src="vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="vendor/circle-progress/circle-progress.min.js"></script>
    <script src="vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="vendor/select2/select2.min.js">
    </script>

    <!-- Main JS-->
    <script src="js/main.js"></script>

</body>

</html>
<!-- end document-->
